gain
oleg-milantiev/allsky.py pull request #109
Opened 2023-05-24 07:14 UTC by flyeye

добавлена работа с гейном и подбор пары выдержка/гейн

2023-05-24 07:30 UTC, oleg-milantiev requested changes

2023-05-24 07:30 UTC, oleg-milantiev commented on allsky.py
> +        global gain
В основном, в файле табуляции. Тут пробелы. Не важно как, но надо одинаково сделать и вести дальше.

В питоне, в основном, используют пробелы (хоть мне нравятся табуляции).

2023-05-24 07:30 UTC, oleg-milantiev commented on allsky.py
> +            (avg >= web['ccd']['avgMin'] and avg <= web['ccd']['avgMax']) or
Мне понравились цепочные сравнения питона. В других языках я о них только думал, а тут они реализованы.

Я про if avgMin <= avg <= avgMax

2023-05-24 07:30 UTC, oleg-milantiev commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
можно сильно упростить и цепочкой, и двумя сравнениями вместо четырёх.

2023-05-24 07:30 UTC, oleg-milantiev commented on allsky.py
>  if hasBinning:
тут я столкнулся, что в INDI драйвере моей старой QHY5 шайбы нет binning.
у меня был Orion круглый, там не было гейна.

Было бы круто учитывать это. Если биннинга нет, не пользоваться им. Если гейна нет ... 

Кстати, моя старая реализации allsky.py (работает у меня в обсерватории до сих пор) переключает bin в 2 ночью и в bin1 днём. Но это другая, более замороченная доделка. Т.к. она влияет на координаты обработчика, на размер лого, на дебаеризацию.

2023-05-24 07:33 UTC, flyeye commented on allsky.py
> +        global gain
Согласен, из-за спешки.

2023-05-24 07:35 UTC, flyeye commented on allsky.py
> +            (avg >= web['ccd']['avgMin'] and avg <= web['ccd']['avgMax']) or
Да, можно

2023-05-24 07:38 UTC, flyeye commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Про цепочку согласен, а вот про два сравнения вместо четырех не уверен...

2023-05-24 07:40 UTC, flyeye commented on allsky.py
>  if hasBinning:
Да, я думал об этом. Решил что если у камеры нет гейна, то можно просто руками ставить gainMin = gainMax и все. Или gainStep ставить в 0 и использовать как флаг (надо немного доделать и протестировать).

2023-05-24 07:45 UTC, oleg-milantiev commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Эта часть

            (avg >= web['ccd']['avgMin'] and avg <= web['ccd']['avgMax']) or 
            ( (exposure <= web['ccd']['expMin']) and (avg >= web['ccd']['avgMax']) and (gain <= web['ccd']['gainMin']) ) or 
            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):

по сути определяет попал ли avg внутрь avgMin..avgMax (первая строка) или вышел ли avg из avgMin..avgMax (else от предыдущего) и при этом вышел ли gain из gainMin..gainMax.

Кажется, так (надо проверить):

            (web['ccd']['avgMin'] <= avg <= web['ccd']['avgMax']) or 
            (gain <= web['ccd']['gainMin']) or
            (gain >= web['ccd']['gainMax'])):

2023-05-24 07:46 UTC, oleg-milantiev commented on allsky.py
>  if hasBinning:
Тож вариант. А в вебе добавить чекбокс "подбирать gain"

2023-05-24 07:53 UTC, flyeye commented on allsky.py
>  if hasBinning:
Настройка в вебе - это будет круто. 
И я тоже думал про разные режимы работы день/ночь. Но тут надо подтягивать библиотеку и вычислять время начала астрономических сумерек на текущую дату. 
Кроме того, похоже даже для ночи мне будут нужны  разные режимы.. Во время навигационных и астрономических сумерек у меня перегорает север, и не видно серебристые облака и северное сияние. Приходится вручную опускать допустимое среднее значение по матрице. А если нужно просто следить за облачностью над обсерваторией то наоборот, поднимать среднее.

2023-05-24 08:07 UTC, flyeye commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Не, это не эквивалент предыдущей системе условий. Мы можем упереться в крайние значения гейн (на очередном шаге), но при этом у нас может возникнуть запас по выдержке.

2023-05-24 10:50 UTC, oleg-milantiev commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Неа. "Запас по выдержке" сработает в первой строке.
Если он не сработал, то проверяем уход по gain на / за границы.

2023-05-24 10:52 UTC, oleg-milantiev commented on allsky.py
>  if hasBinning:
> И я тоже думал про разные режимы работы день/ночь. Но тут надо подтягивать библиотеку и вычислять время начала астрономических сумерек на текущую дату.

и да, и нет. Я тоже сначал думал привязываться к времени. Но потом взошла Луна. А ещё под локальную засветку попало или не попало обралок.

Лучше, мне кажется, строить универсальную систему подбора вилки экспозиции / gain / bin.
Хоть это может привести к слишком длительному поиску. Но за это будет отвечать maxAttempt и, в целом, медленная скорость изменения яркости неба.

2023-05-24 11:12 UTC, flyeye commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Неа. Первая строчка про среднее значение пикселя, а не про выдержку. Они конечно связаны, но не тождественны.

2023-05-24 11:14 UTC, flyeye commented on allsky.py
>  if hasBinning:
Ну, Луна засвечивает небо не так сильно, как Солнце в сумерки. А местная засветка более-менее постоянна. Но в целом я согласен, что иметь один продвинутый алгоритм лучше, чем несколько. Предлагаю отложить это все на будущее.

2023-05-24 11:25 UTC, oleg-milantiev commented on allsky.py
> +            ( (exposure == web['ccd']['expMax']) and (avg < web['ccd']['avgMin']) and ( gain >= web['ccd']['gainMax'])):
Блин, точно! Ступил :)

2023-10-27 18:03 UTC, oleg-milantiev commented
Код из этого PR был добавлен в ветку docker

2023-10-27 18:03 UTC, closed without merging